[package]
name = "codcel-postgresql-engine"
version = "0.1.9"
edition = "2021"
authors = ["Codcel <support@codcel.io>"]
description = "PostgreSQL table implementation for Codcel, providing Excel-like lookup and filter operations backed by PostgreSQL."
documentation = "https://codcel.io"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/codcel-io/codcel-postgresql-engine"
homepage   = "https://codcel.io"
keywords = ["excel", "finance", "codcel", "spreadsheet", "functions"]
categories = ["mathematics", "finance"]

[dependencies]
codcel-calculation-engine = { git = "https://github.com/codcel-io/codcel-calculation-engine.git", branch = "pre-release-0.1.9" }
codcel-table-engine = { git = "https://github.com/codcel-io/codcel-table-engine.git", branch = "pre-release-0.1.9" }
async-trait = "0.1.91"
datafusion = "54.1.0"
sqlx = { version = "0.9.0", features = ["runtime-tokio", "postgres"] }
anyhow = "1.0.104"
chrono = "0.4.45"
uuid = { version = "1.24.0", features = ["v4"] }
whoami = "2.1.2"
log = "0.4.33"
futures = "0.3.33"
